[programs.devnet]
myepicproject = "2XoLYMFMeqH5mCobEYpqj6FZSWsYXj99g8n56mqTt8eG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/jobodo/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
